# Generated by Django 4.2.11 on 2024-05-14 05:22

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255)),
                ('price', models.IntegerField()),
                ('product_category', models.CharField(choices=[('phone', 'phone'), ('computer', 'computer'), ('smart_watch', 'smart watch'), ('headphone', 'headphone'), ('gaming', 'gaming'), ('camera', 'camera')], max_length=255)),
                ('discription', models.TextField()),
                ('date', models.DateField(default=datetime.datetime.now)),
                ('discount', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('rating', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('no_of_people_rated', models.PositiveIntegerField()),
            ],
        ),
    ]
