# Generated by Django 4.2.11 on 2024-05-20 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_spotlight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spotlight',
            name='image',
            field=models.ImageField(upload_to='spotlight/'),
        ),
        migrations.AlterField(
            model_name='spotlight',
            name='logo',
            field=models.ImageField(upload_to='spotlight/'),
        ),
    ]
